### ISSUE TITLE
Server Crash on Client Join

### ISSUE THREAD

**Issue by SteveKnowless** [Shnupbups/TinkersAether#7]
Minecraft: 1.12.2
Forge: 14.23.4.2705
tinkersaether: 1.1.2

When client Joins server, server crashes. This does not happen with the previous version (1.1.1)

`
Time: 7/4/18 11:50 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.ai.attributes.IAttributeInstance.func_142049_d()V
	at shnupbups.tinkersaether.traits.Reach.onPlayerJoin(Reach.java:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_770_Reach_onPlayerJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1205)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:376)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:165)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source
)
`

**Comment by Shnupbups** [comment]
Whoops! Noted, will fix ASAP.

**Comment by Shnupbups** [comment]
Fixed in 1.1.3.

**Comment by SteveKnowless** [comment]
Confirmed Fixed. Thank you for the quick response!
